/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VendingMachine;

import FrontEnd.AlertWindow;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.stage.Stage;
import java.io.IOException;

public class App extends Application {
    private static Stage stage;

    @Override
    public void start(Stage primaryStage) throws Exception {
        stage = primaryStage;
        primaryStage.setResizable(false);
        Parent root = FXMLLoader.load(getClass().getClassLoader().getResource("MainMenu.fxml"));
        Scene scene = new Scene(root);
        primaryStage.setTitle("Vending Machine");
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    public void changeScene(String fxml, String title) {
        try {
            Parent pane = FXMLLoader.load(getClass().getClassLoader().getResource(fxml));
            stage.getScene().setRoot(pane);
            stage.setTitle(title);
        } catch (IOException e) {
            e.printStackTrace();
            System.out.println("unsuccessfully read fxml file ");
        }
    }

    public static void main(String[] args) {
        // default anonymous customer
        AppData.setCustomer(UserData.getAnonymousCustomer());
        // get initial product data
        ProductData.readInventory();

        launch(args);
    }
}